# This is a basic workflow to help you get started with Action
name: test 1
on: [push]
env:
  variable: var1
jobs:
  job1:
    runs-on: ubuntu-latest 
    env: 
      toto: var2
    steps:
    - uses: actions/checkout@v3
    - name : hello world !
      run: echo "hello world !"
      run: echo $variable
      run: echo $toto
  job2:
  runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name : hello world !
      run: echo $toto
      

 
